const cfg=window.STACKOPS_CONFIG||{};
const ready=cfg.SUPABASE_URL&&!cfg.SUPABASE_URL.includes('YOUR_')&&cfg.SUPABASE_ANON_KEY&&!cfg.SUPABASE_ANON_KEY.includes('YOUR_');
const db=ready?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
let user=null, me=null, cache={profiles:[],plans:[],services:[],squads:[],orders:[],badges:[]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const toast=m=>{let t=document.createElement('div');t.textContent=m;$('#toast').appendChild(t);setTimeout(()=>t.remove(),3500)};
const img=n=>`https://api.dicebear.com/8.x/bottts/svg?seed=${encodeURIComponent(n||'stackops')}`;
function route(id){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+id).classList.add('active'); if(id==='admin') renderAdmin('users'); scrollTo({top:0,behavior:'smooth'});} 
$$('[data-route]').forEach(b=>b.onclick=()=>route(b.dataset.route));
function modal(title,html){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modal').classList.remove('hide')}
$('#closeModal').onclick=()=>$('#modal').classList.add('hide');
$('#authOpen').onclick=()=> user?route('profile'):authModal();
function authModal(){modal('Enter StackOps',`<input id="em" placeholder="Email"><input id="pw" type="password" placeholder="Password"><button class="primary" id="login">Login</button> <button class="ghost" id="signup">Create Account</button>`);$('#login').onclick=login;$('#signup').onclick=signup}
async function login(){if(!db)return toast('Add Supabase URL and anon key in config.js');let {error}=await db.auth.signInWithPassword({email:$('#em').value,password:$('#pw').value}); if(error)return toast(error.message); $('#modal').classList.add('hide'); await boot();}
async function signup(){if(!db)return toast('Add Supabase URL and anon key in config.js');let {error}=await db.auth.signUp({email:$('#em').value,password:$('#pw').value}); if(error)return toast(error.message); toast('Account created. Login after email confirmation if enabled.');}
async function boot(){stars(); if(!db){demo();return} let s=await db.auth.getSession(); user=s.data.session?.user||null; db.auth.onAuthStateChange(()=>boot()); if(user){$('#authOpen').textContent='Profile'; await loadMe();}else{$('#authOpen').textContent='Login';$('#adminNav').classList.add('hide')} await loadAll(); renderAll();}
async function loadMe(){let {data,error}=await db.from('profiles').select('*').eq('id',user.id).maybeSingle(); if(!data&&!error){await db.from('profiles').insert({id:user.id,username:user.email?.split('@')[0],display_name:user.email?.split('@')[0]}); data=(await db.from('profiles').select('*').eq('id',user.id).single()).data} me=data; $('#adminNav').classList.toggle('hide',me?.role!=='admin'); fillProfile();}
async function loadAll(){let qs=[db.from('profiles').select('*').order('created_at',{ascending:false}),db.from('plans').select('*').order('price_inr'),db.from('services').select('*,profiles(display_name,avatar_url)').order('created_at',{ascending:false}),db.from('squads').select('*').order('created_at',{ascending:false}),db.from('orders').select('*').order('created_at',{ascending:false}),db.from('badges').select('*')];let r=await Promise.all(qs);['profiles','plans','services','squads','orders','badges'].forEach((k,i)=>cache[k]=r[i].data||[])}
function renderAll(){renderPlayers();renderPlans();renderServices();renderSquads();renderBadges()}
function fillProfile(){if(!me)return;$('#displayName').value=me.display_name||'';$('#riotId').value=me.riot_id||'';$('#rank').value=me.rank||'';$('#region').value=me.region||'India';$('#bio').value=me.bio||'';$('#avatarImg').src=me.avatar_url||img(me.id)}
$('#saveProfile').onclick=async()=>{if(!user)return authModal();let patch={display_name:$('#displayName').value,riot_id:$('#riotId').value,rank:$('#rank').value,region:$('#region').value,bio:$('#bio').value,account_status:me?.account_status==='pending'?'approved':me?.account_status};let {error}=await db.from('profiles').update(patch).eq('id',user.id); if(error)return toast(error.message); toast('Profile saved'); await boot()}
$('#avatarFile').onchange=async e=>{if(!user)return authModal();let f=e.target.files[0]; if(!f)return;let path=`${user.id}/${Date.now()}-${f.name.replace(/\s/g,'-')}`;let up=await db.storage.from('avatars').upload(path,f,{upsert:true}); if(up.error)return toast(up.error.message);let url=db.storage.from('avatars').getPublicUrl(path).data.publicUrl;await db.from('profiles').update({avatar_url:url}).eq('id',user.id);toast('Avatar uploaded');await boot()}
function playerCard(p){let admin=p.role==='admin';return `<div class="card"><img class="mini" src="${p.avatar_url||img(p.id)}"><h3>${admin?'♛ ':''}${p.display_name||p.username||'Player'}</h3><p>${p.riot_id||'No Riot ID'} • ${p.rank||'Unranked'} • ${p.region||'Global'}</p><span class="badge">${p.title||p.badge||p.plan_key||'Rookie'}</span><div class="actions"><button class="primary invite" data-id="${p.id}">Invite</button><button class="ghost">Add Friend</button></div></div>`}
function renderPlayers(){let q=($('#playerSearch')?.value||'').toLowerCase();let arr=cache.profiles.filter(p=>!q||JSON.stringify(p).toLowerCase().includes(q));$('#players').innerHTML=arr.map(playerCard).join('')||'<p class="muted">No players yet.</p>';$$('.invite').forEach(b=>b.onclick=()=>toast('Invite sent / saved for UI. Add realtime table later.'))}
$('#playerSearch').oninput=renderPlayers;$('#refreshPlayers').onclick=async()=>{if(db){await loadAll();renderPlayers();toast('Players refreshed')}};
function renderPlans(){let plans=cache.plans.length?cache.plans:demoPlans();$('#plansList').innerHTML=plans.map(p=>`<div class="card"><h3>${p.name}</h3><div class="price">₹${p.price_inr}</div><p>${p.title||p.title_reward||''}</p><span class="badge">${p.badge||'Premium'}</span><button class="primary buy" data-key="${p.plan_key}">Request Plan</button></div>`).join('');$$('.buy').forEach(b=>b.onclick=()=>buyPlan(b.dataset.key))}
async function buyPlan(key){if(!user)return authModal();let p=(cache.plans.length?cache.plans:demoPlans()).find(x=>x.plan_key===key);let {error}=await db.from('orders').insert({buyer_id:user.id,plan_key:key,amount_inr:p.price_inr,status:'pending',platform_commission_inr:0}); if(error)return toast(error.message);toast('Plan request sent. Admin will verify payment.');}
function renderServices(){let list=cache.services.filter(s=>s.status==='approved'||me?.role==='admin'||s.owner_id===user?.id);$('#servicesList').innerHTML=list.map(s=>`<div class="card"><h3>${s.title}</h3><p>${s.description||''}</p><div class="price">₹${s.price_inr}</div><p>Commission: ${s.commission_percent||15}% • ${s.status}</p><button class="primary">Book / Request</button></div>`).join('')||'<p class="muted">No services yet. List one.</p>'}
$('#newService').onclick=()=>{if(!user)return authModal();modal('List Service',`<input id="st" placeholder="Title"><input id="sp" type="number" placeholder="Price ₹"><textarea id="sd" placeholder="Description"></textarea><button id="ss" class="primary">Submit for Approval</button>`);$('#ss').onclick=async()=>{let {error}=await db.from('services').insert({owner_id:user.id,title:$('#st').value,price_inr:+$('#sp').value||499,description:$('#sd').value,status:'pending',commission_percent:cfg.PLATFORM_COMMISSION_PERCENT||15});if(error)return toast(error.message);$('#modal').classList.add('hide');toast('Service sent to admin');await boot()}}
function renderSquads(){let list=cache.squads;$('#squadsList').innerHTML=list.map(s=>`<div class="card"><h3>${s.name}</h3><p>${s.game||'Valorant'} • ${s.region||'Global'} • ${s.rank_required||'Any rank'}</p><button class="primary">Join / Invite</button></div>`).join('')||'<p class="muted">No squads yet.</p>'}
$('#newSquad').onclick=()=>{if(!user)return authModal();modal('Create Squad',`<input id="sn" placeholder="Squad name"><input id="sr" placeholder="Rank required"><button id="sc" class="primary">Create</button>`);$('#sc').onclick=async()=>{let {error}=await db.from('squads').insert({owner_id:user.id,name:$('#sn').value,rank_required:$('#sr').value,game:'Valorant'});if(error)return toast(error.message);$('#modal').classList.add('hide');toast('Squad created');await boot()}}
function renderBadges(){let b=cache.badges.length?cache.badges:demoBadges();$('#badgesList').innerHTML=b.map(x=>`<div class="card"><h3>${x.icon||'◆'} ${x.name}</h3><p>${x.description||x.rarity||'Reward badge'}</p><span class="badge">${x.rarity||'Rare'}</span></div>`).join('')}
$$('[data-tab]').forEach(b=>b.onclick=()=>renderAdmin(b.dataset.tab));
function renderAdmin(tab='users'){if(me?.role!=='admin'){$('#adminBox').innerHTML='<p class="muted">Admin only.</p>';return}$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));let html='';if(tab==='users')html=cache.profiles.map(p=>`<div class="card row"><div><h3>${p.role==='admin'?'♛ ':''}${p.display_name||p.username}</h3><p>${p.id}<br>${p.account_status} • ${p.role} • ${p.plan_key||'free'}</p></div><div class="actions"><button class="ok" onclick="adminUser('${p.id}','approved')">Approve</button><button class="warn" onclick="makeAdmin('${p.id}')">Admin</button><button class="danger" onclick="adminUser('${p.id}','banned')">Ban</button></div></div>`).join('');if(tab==='services')html=cache.services.map(s=>`<div class="card row"><div><h3>${s.title}</h3><p>₹${s.price_inr} • ${s.status}</p></div><div class="actions"><button class="ok" onclick="serviceStatus('${s.id}','approved')">Approve</button><button class="danger" onclick="serviceStatus('${s.id}','rejected')">Reject</button></div></div>`).join('');if(tab==='orders')html=cache.orders.map(o=>`<div class="card row"><div><h3>${o.plan_key||'Order'}</h3><p>₹${o.amount_inr} • ${o.status} • buyer ${o.buyer_id}</p></div><div class="actions"><button class="ok" onclick="orderStatus('${o.id}','paid','${o.buyer_id}','${o.plan_key}')">Verify</button><button class="danger" onclick="orderStatus('${o.id}','cancelled')">Reject</button></div></div>`).join('');$('#adminBox').innerHTML=html||'<p class="muted">Nothing here.</p>'}
window.adminUser=async(id,status)=>{await db.from('profiles').update({account_status:status,is_banned:status==='banned'}).eq('id',id);toast('User updated');await boot();renderAdmin('users')}
window.makeAdmin=async id=>{await db.from('profiles').update({role:'admin',title:'Founder Admin',badge:'Admin Crown',account_status:'approved',is_verified:true}).eq('id',id);toast('Admin crown granted');await boot();renderAdmin('users')}
window.serviceStatus=async(id,status)=>{await db.from('services').update({status}).eq('id',id);toast('Service updated');await boot();renderAdmin('services')}
window.orderStatus=async(id,status,buyer,plan)=>{await db.from('orders').update({status}).eq('id',id); if(status==='paid'&&buyer&&plan){let p=cache.plans.find(x=>x.plan_key===plan);await db.from('profiles').update({plan_key:plan,title:p?.title,badge:p?.badge}).eq('id',buyer)}toast('Order updated');await boot();renderAdmin('orders')}
function demoPlans(){return[{plan_key:'free',name:'Free',price_inr:0,badge:'Starter',title:'Rookie'},{plan_key:'silver',name:'Silver',price_inr:499,badge:'Silver Badge',title:'Rising Gamer'},{plan_key:'gold',name:'Gold',price_inr:1499,badge:'Gold Badge',title:'Elite Player'},{plan_key:'diamond',name:'Diamond',price_inr:4999,badge:'Diamond Badge',title:'Pro Grinder'},{plan_key:'legend',name:'Legend',price_inr:10000,badge:'Crown Badge',title:'StackOps Legend'}]}
function demoBadges(){return[{icon:'♛',name:'Admin Crown',rarity:'Mythic',description:'Special admin name banner and crown.'},{icon:'◆',name:'Verified Coach',rarity:'Epic'},{icon:'⚡',name:'Squad Hunter',rarity:'Rare'},{icon:'✦',name:'Founder',rarity:'Legendary'}]}
function demo(){cache.profiles=[{id:'1',display_name:'RadiantRex',riot_id:'Rex#999',rank:'Radiant',region:'India',title:'Founder',role:'admin'},{id:'2',display_name:'SageQueen',riot_id:'Heal#SEA',rank:'Immortal',region:'SEA'}];cache.plans=demoPlans();cache.badges=demoBadges();cache.services=[{title:'Valorant Aim Coaching',description:'1 hour aim + crosshair placement session',price_inr:499,status:'approved',commission_percent:15}];cache.squads=[{name:'Night Queue Hunters',rank_required:'Gold+',region:'India'}];renderAll();toast('Demo mode. Add Supabase keys in config.js for real backend.')}
function stars(){let c=$('#space'),x=c.getContext('2d'),w,h,pts=[];function size(){w=c.width=innerWidth;h=c.height=innerHeight;pts=Array.from({length:90},()=>({x:Math.random()*w,y:Math.random()*h,z:Math.random()*2+0.4}))}size();addEventListener('resize',size);(function loop(){x.clearRect(0,0,w,h);x.fillStyle='#ffffff88';pts.forEach(p=>{p.y+=p.z;if(p.y>h)p.y=0;x.beginPath();x.arc(p.x,p.y,p.z,0,7);x.fill()});requestAnimationFrame(loop)})()}
boot();
