const $=(q,el=document)=>el.querySelector(q), $$=(q,el=document)=>[...el.querySelectorAll(q)];
const cfg=window.STACKOPS_CONFIG||{};
const sb=cfg.SUPABASE_URL && !cfg.SUPABASE_URL.includes('YOUR_') && cfg.SUPABASE_ANON_KEY && !cfg.SUPABASE_ANON_KEY.includes('YOUR_') ? supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY) : null;
const adminEmails=(cfg.ADMIN_EMAILS||[]).map(x=>String(x).toLowerCase().trim()).filter(Boolean);
const S={user:null,profile:null,counts:{gamers:1240,squads:86,coaches:21,events:9},squads:[],services:[],posts:[],plans:[],profiles:[],payments:[]};
const rupee=n=>'₹'+Number(n||0).toLocaleString('en-IN');
const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const toast=m=>{const t=$('#toast'); if(!t)return; t.textContent=m; t.classList.add('show'); clearTimeout(window.__toast); window.__toast=setTimeout(()=>t.classList.remove('show'),2300)};
const isAdmin=()=>String(S.profile?.role||'').toLowerCase()==='admin'||adminEmails.includes(String(S.user?.email||'').toLowerCase());
const uid=()=>S.user?.id;

document.addEventListener('DOMContentLoaded',init);
async function init(){bind(); setTimeout(()=>$('#intro')?.classList.add('hide'),900); await auth(); await loadAll(); route();}
function bind(){window.addEventListener('hashchange',route); $('#menuBtn')?.addEventListener('click',()=>openDrawer()); $$('[data-close],.drawer-bg').forEach(x=>x.addEventListener('click',closeDrawer)); $('#accountBtn')?.addEventListener('click',()=>S.user?location.hash='profile':authModal()); $('#scrollTop')?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'})); addEventListener('scroll',()=>$('#scrollTop')?.classList.toggle('show',scrollY>500)); document.body.addEventListener('click',globalClick); document.body.addEventListener('submit',globalSubmit);}
function openDrawer(){const d=$('#drawer'); d?.classList.add('open'); d?.setAttribute('aria-hidden','false')}
function closeDrawer(){const d=$('#drawer'); d?.classList.remove('open'); d?.setAttribute('aria-hidden','true')}
async function auth(){if(!sb){updateAccount();return} const {data}=await sb.auth.getUser(); S.user=data?.user||null; await loadProfile(); updateAccount();}
async function loadProfile(){if(!sb||!S.user){S.profile=null;return} let {data}=await sb.from('profiles').select('*').eq('id',uid()).maybeSingle(); if(!data){await sb.from('profiles').insert({id:uid(),username:(S.user.email||'gamer').split('@')[0],display_name:(S.user.email||'Gamer').split('@')[0],role:adminEmails.includes(String(S.user.email).toLowerCase())?'admin':'user',account_status:'approved'}); ({data}=await sb.from('profiles').select('*').eq('id',uid()).maybeSingle());} if(data && adminEmails.includes(String(S.user.email).toLowerCase()) && data.role!=='admin'){await sb.from('profiles').update({role:'admin',account_status:'approved',title:'Founder 👑',badge:'Admin Crown',is_verified:true,is_banned:false}).eq('id',uid()); data.role='admin'; data.account_status='approved'; data.title='Founder 👑'; data.badge='Admin Crown'; data.is_verified=true;} S.profile=data;}
async function loadAll(){await Promise.all([loadPlans(),loadSquads(),loadServices(),loadPosts(),loadCounts(),loadAdminData()]);}
async function loadCounts(){if(!sb)return; const tables=[['profiles','gamers'],['squads','squads'],['services','coaches'],['events','events']]; for(const [t,k] of tables){try{const {count}=await sb.from(t).select('*',{count:'exact',head:true}); if(count!==null)S.counts[k]=count}catch(e){}}}
async function loadPlans(){if(!sb){S.plans=localPlans();return} const {data}=await sb.from('plans').select('*').order('price_inr'); S.plans=data?.length?data:localPlans();}
async function loadSquads(){if(!sb){S.squads=localSquads();return} const {data}=await sb.from('squads').select('*').order('created_at',{ascending:false}).limit(24); S.squads=data?.length?data:localSquads();}
async function loadServices(){if(!sb){S.services=localServices();return} const {data}=await sb.from('services').select('*').order('created_at',{ascending:false}).limit(24); S.services=data?.length?data:localServices();}
async function loadPosts(){if(!sb){S.posts=localPosts();return} const {data}=await sb.from('posts').select('*').order('created_at',{ascending:false}).limit(24); S.posts=data?.length?data:localPosts();}
async function loadAdminData(){if(!sb||!isAdmin())return; const [p,sv,pay]=await Promise.all([sb.from('profiles').select('*').order('created_at',{ascending:false}).limit(40),sb.from('services').select('*').order('created_at',{ascending:false}).limit(40),sb.from('payments').select('*').order('created_at',{ascending:false}).limit(40).catch(()=>({data:[]}))]); S.profiles=p.data||[]; S.services=sv.data?.length?sv.data:S.services; S.payments=pay.data||[];}
function updateAccount(){const html=S.user?`<b>${esc(S.profile?.display_name||S.user.email)}</b><small>${isAdmin()?'👑 Admin access':'Gamer account'} • ${esc(S.profile?.title||'Rookie')}</small><button id="logout" class="ghost small">Logout</button>`:`<b>Guest Gamer</b><small>Login to join squads, buy plans and post.</small><button id="openLogin" class="btn small">Login</button>`; const da=$('#drawerAccount'); if(da)da.innerHTML=html; const ab=$('#accountBtn'); if(ab)ab.textContent=S.user?(isAdmin()?'👑 Admin':'Profile'):'Login';}
function route(){closeDrawer(); const raw=(location.hash||'#home').replace('#',''); const [name,id]=raw.split('/'); const pages={home,lobby,squads,services,plans,rewards,feed,profile,admin,setup}; const fn=pages[name]||home; $('#app').innerHTML=fn(id); afterRender(name);}
function afterRender(name){animateCounters(); if(name==='profile') bindProfileUpload();}
function animateCounters(){$$('.live-num').forEach(el=>{const target=Number(el.dataset.count)||0; let start=0,frames=28; const step=()=>{start++; el.textContent=Math.round(target*start/frames).toLocaleString('en-IN'); if(start<frames)requestAnimationFrame(step)}; step()})}
function home(){return `<section class="hero reveal"><div class="hero-copy"><p class="eyebrow">Riot-style social lobby • Supabase powered</p><h1>Make gamers feel like they entered a <span class="gradient-text">private esports universe.</span></h1><p>StackOps Nexus mixes Discord energy, Instagram profiles, squad discovery, coaching marketplace, paid plans, badges, and an admin command center — without heavy laggy effects.</p><div class="hero-actions"><button class="btn" data-route="lobby">Enter Live Lobby</button><button class="ghost" data-route="squads">Find Squad</button><button class="ghost" data-route="services">Book Coaching</button></div></div><div class="hero-stage"><div class="lobby-card"><p class="eyebrow">Live party pulse</p><div class="agent-line"><div class="avatar-stack"><i>J</i><i>R</i><i>V</i><i>+</i></div><div><b>Radiant Rush Squad</b><small class="muted">Mumbai • Valorant • Competitive</small></div></div><div class="rank-meter"><i></i></div></div><div class="mini-feed"><div><span>🎯 Coach verified</span><b>2 min ago</b></div><div><span>👑 Admin approved 4 users</span><b>live</b></div><div><span>⚡ New Immortal squad opened</span><b>now</b></div></div><div class="lobby-card"><p class="eyebrow">Your next action</p><h3>Build profile → earn badge → join better squads.</h3><button class="btn small" data-route="profile">Upgrade Identity</button></div></div></section>${stats()}${features()}${lobby()}`}
function stats(){return `<section class="stats reveal"><div class="stat"><b class="live-num" data-count="${S.counts.gamers}">0</b><span>Gamers synced</span></div><div class="stat"><b class="live-num" data-count="${S.counts.squads}">0</b><span>Open squads</span></div><div class="stat"><b class="live-num" data-count="${S.counts.coaches}">0</b><span>Coaches/services</span></div><div class="stat"><b class="live-num" data-count="${S.counts.events}">0</b><span>Live events</span></div></section>`}
function features(){const f=[['⚡','Instant squads','Rank, region and playstyle cards designed for quick invites.'],['👑','Admin crown system','Admins get special banners, titles, crown identity and full moderation tools.'],['🎓','Coaching marketplace','Verified coaches can sell sessions while platform earns commission.'],['🏆','Badges & quests','Gamified titles, rewards and premium plan benefits.'],['💬','Social feed','Post clips, updates and recruitment calls.'],['💸','Monetization ready','Plans up to ₹10,000, payments table and verification workflow.']];return `<section class="section reveal"><div class="section-head"><div><p class="eyebrow">Fun but clean</p><h2>Not boring. Not laggy.</h2></div><p class="muted">Smooth CSS motion, live counters and interactive cards inspired by your reference site, but gamer-first.</p></div><div class="grid three">${f.map(x=>`<article class="card"><div class="feature-icon">${x[0]}</div><h3>${x[1]}</h3><p class="muted">${x[2]}</p></article>`).join('')}</div></section>`}
function lobby(){return `<section class="section reveal"><div class="section-head"><div><p class="eyebrow">Live lobby</p><h2>What is happening now.</h2></div><button class="btn small" data-route="feed">Open Feed</button></div><div class="grid three">${localLive().map(x=>`<article class="card"><span class="tag ${x.hot?'hot':''}">${x.tag}</span><h3>${x.title}</h3><p class="muted">${x.text}</p><div class="badge-row"><span class="badge">${x.a}</span><span class="badge">${x.b}</span></div></article>`).join('')}</div></section>`}
function squads(){return `<section class="section reveal"><div class="section-head"><div><p class="eyebrow">Squad finder</p><h2>Find or create a party.</h2></div><button class="btn small" onclick="document.getElementById('squadForm').classList.toggle('hidden')">Create Squad</button></div><form id="squadForm" class="card forms hidden"><input name="name" placeholder="Squad name" required><div class="grid two"><input name="game" placeholder="Game" value="Valorant"><input name="region" placeholder="Region e.g. Mumbai / Singapore"></div><input name="rank_required" placeholder="Rank required"><textarea name="description" placeholder="Playstyle, timing, rules"></textarea><button class="btn">Publish Squad</button></form><div class="grid three">${S.squads.map(squadCard).join('')}</div></section>`}
function squadCard(s){return `<article class="card squad-card"><span class="tag">${esc(s.game||'Valorant')}</span><h3>${esc(s.name)}</h3><p class="muted">${esc(s.description||'Looking for clean comms and good vibes.')}</p><div class="squad-meta"><span class="badge">📍 ${esc(s.region||'Any region')}</span><span class="badge">🏅 ${esc(s.rank_required||'Any rank')}</span></div><button class="btn small" data-join-squad="${esc(s.id)}">Request Invite</button></article>`}
function services(){return `<section class="section reveal"><div class="section-head"><div><p class="eyebrow">Coaching & services</p><h2>Earn through verified gaming skills.</h2></div><button class="btn small" onclick="document.getElementById('serviceForm').classList.toggle('hidden')">Sell Service</button></div><form id="serviceForm" class="card forms hidden"><input name="title" placeholder="Service title e.g. Valorant Aim Coaching" required><textarea name="description" placeholder="What you provide"></textarea><div class="grid three"><input name="game" value="Valorant"><select name="category"><option>coaching</option><option>rank-review</option><option>team-finder</option><option>profile-verification</option></select><input name="price_inr" type="number" placeholder="Price in INR" required></div><button class="btn">Submit for Admin Approval</button></form><div class="grid three">${S.services.map(serviceCard).join('')}</div></section>`}
function serviceCard(s){return `<article class="card service-card"><span class="tag ${s.status==='approved'?'hot':''}">${esc(s.status||'pending')}</span><h3>${esc(s.title)}</h3><p class="muted">${esc(s.description||'Premium gamer service.')}</p><div class="service-meta"><span class="badge">🎮 ${esc(s.game||'Valorant')}</span><span class="badge">💰 ${rupee(s.price_inr)}</span><span class="badge">📈 ${s.commission_percent||15}% commission</span></div><button class="btn small" data-buy-service="${esc(s.id)}">Book / Pay Request</button></article>`}
function plans(){return `<section class="section reveal"><div class="section-head"><div><p class="eyebrow">Premium plans</p><h2>Badges, boosts and status.</h2></div><p class="muted">Frontend creates payment intent records; connect Razorpay webhook later for automatic verification.</p></div><div class="grid three">${S.plans.map(p=>`<article class="card plan ${p.plan_key==='legend'?'legend':''}"><span class="tag ${p.plan_key==='legend'?'hot':''}">${esc(p.badge)}</span><h3>${esc(p.name)}</h3><div class="price">${rupee(p.price_inr)}</div><p class="muted">${esc(p.title)} • ${Array.isArray(p.perks)?p.perks.join(', '):esc(p.perks||'Premium perks')}</p><button class="btn small" data-buy-plan="${esc(p.plan_key)}">Choose Plan</button></article>`).join('')}</div></section>`}
function rewards(){const b=['Starter','Clutch King','Aim Demon','Squad Leader','Verified Coach','Gold Elite','Diamond Pro','StackOps Legend','Admin Crown','Founder 👑'];return `<section class="section reveal"><p class="eyebrow">Rewards system</p><h2>Titles that make profiles feel special.</h2><div class="grid three">${b.map((x,i)=>`<article class="card"><span class="feature-icon">${i>7?'👑':i>4?'💎':'🏆'}</span><h3>${x}</h3><p class="muted">Unlock through plans, coaching, quests or admin verification.</p></article>`).join('')}</div></section>`}
function feed(){return `<section class="section reveal"><div class="section-head"><div><p class="eyebrow">Social feed</p><h2>Clips, invites and updates.</h2></div></div><form id="postForm" class="card feed-composer"><textarea name="content" placeholder="Post a clip link, squad call, achievement or update..."></textarea><button class="btn">Post</button></form><div class="grid two">${S.posts.map(postCard).join('')}</div></section>`}
function postCard(p){return `<article class="card post"><div class="post-head"><span class="post-avatar">${esc((p.display_name||'G')[0])}</span><div><b>${esc(p.display_name||'Gamer')}</b><small class="muted">${new Date(p.created_at||Date.now()).toLocaleString()}</small></div></div><p>${esc(p.content||'Ready to queue?')}</p><div class="badge-row"><span class="badge">🔥 Hype</span><span class="badge">💬 Reply</span><span class="badge">➕ Invite</span></div></article>`}
function profile(){const p=S.profile||{};return `<section class="section reveal"><div class="section-head"><div><p class="eyebrow">Gamer identity</p><h2>${isAdmin()?'👑 ':''}${esc(p.display_name||'Your Profile')}</h2></div><span class="tag ${isAdmin()?'hot':''}">${esc(p.title||'Rookie')}</span></div>${!S.user?`<div class="card"><h3>Login required</h3><p class="muted">Create your gamer identity first.</p><button class="btn" id="openLogin">Login</button></div>`:`<div class="grid two"><form id="profileForm" class="card forms"><input name="display_name" value="${esc(p.display_name||'')}" placeholder="Display name"><input name="username" value="${esc(p.username||'')}" placeholder="Username"><input name="riot_id" value="${esc(p.riot_id||'')}" placeholder="Riot ID"><div class="grid two"><input name="region" value="${esc(p.region||'')}" placeholder="Region"><input name="main_game" value="${esc(p.main_game||'Valorant')}" placeholder="Main game"></div><textarea name="bio" placeholder="Bio">${esc(p.bio||'')}</textarea><button class="btn">Save Profile</button></form><div class="card"><p class="eyebrow">Status card</p><h3>${isAdmin()?'Admin Crown Active':'Build your reputation'}</h3><div class="badge-row"><span class="badge">${esc(p.badge||'Starter')}</span><span class="badge">${esc(p.plan_key||'free')}</span><span class="badge">${p.is_verified?'✅ Verified':'⏳ Not verified'}</span></div><p class="muted">Admin by email is supported in config.js and SQL. Your admin banner appears automatically after login.</p></div></div>`}</section>`}
function admin(){if(!S.user)return `<section class="section"><div class="card"><h2>Admin login</h2><p class="muted">Login with an email listed in config.js and SQL admin_emails table.</p><button class="btn" id="openLogin">Login</button></div></section>`; if(!isAdmin())return `<section class="section"><div class="card"><h2>Not admin</h2><p class="muted">Your email is not configured as an admin yet.</p></div></section>`;return `<section class="section reveal"><div class="section-head"><div><p class="eyebrow">Command center</p><h2>👑 Admin console</h2></div><button class="btn small" data-refresh-admin>Refresh</button></div><div class="grid three"><div class="card"><b class="live-num" data-count="${S.profiles.length}">0</b><span class="muted">Loaded users</span></div><div class="card"><b class="live-num" data-count="${S.services.filter(x=>x.status==='pending').length}">0</b><span class="muted">Pending services</span></div><div class="card"><b class="live-num" data-count="${S.payments.filter(x=>x.status==='pending').length}">0</b><span class="muted">Pending payments</span></div></div><section class="section"><h2>Users</h2><div class="card">${adminUsersTable()}</div></section><section class="section"><h2>Services</h2><div class="card">${adminServicesTable()}</div></section><section class="section"><h2>Payments</h2><div class="card">${adminPaymentsTable()}</div></section></section>`}
function adminUsersTable(){return `<table class="table"><tr><th>User</th><th>Role</th><th>Status</th><th>Action</th></tr>${S.profiles.map(p=>`<tr><td><b>${esc(p.display_name||p.username||p.id)}</b><br><small>${esc(p.id)}</small></td><td>${esc(p.role)}</td><td>${esc(p.account_status)} ${p.is_banned?'• banned':''}</td><td><button class="btn small" data-admin-user="approve:${p.id}">Approve</button> <button class="ghost small" data-admin-user="verify:${p.id}">Verify</button> <button class="ghost small danger" data-admin-user="ban:${p.id}">Ban</button></td></tr>`).join('')}</table>`}
function adminServicesTable(){return `<table class="table"><tr><th>Service</th><th>Price</th><th>Status</th><th>Action</th></tr>${S.services.map(s=>`<tr><td><b>${esc(s.title)}</b><br><small>${esc(s.game)} • ${esc(s.category)}</small></td><td>${rupee(s.price_inr)}</td><td>${esc(s.status)}</td><td><button class="btn small" data-admin-service="approved:${s.id}">Approve</button> <button class="ghost small danger" data-admin-service="rejected:${s.id}">Reject</button></td></tr>`).join('')}</table>`}
function adminPaymentsTable(){return `<table class="table"><tr><th>Payment</th><th>Amount</th><th>Status</th><th>Action</th></tr>${S.payments.map(p=>`<tr><td><b>${esc(p.purpose||p.plan_key||'Payment')}</b><br><small>${esc(p.id)}</small></td><td>${rupee(p.amount_inr)}</td><td>${esc(p.status)}</td><td><button class="btn small" data-admin-payment="verified:${p.id}">Verify</button><button class="ghost small danger" data-admin-payment="rejected:${p.id}">Reject</button></td></tr>`).join('')||'<tr><td colspan="4">No payments yet.</td></tr>'}</table>`}
function setup(){return `<section class="section reveal"><div class="card"><p class="eyebrow">Setup guide</p><h2>SQL REQUIRED: YES</h2><p class="muted">Run database-clean-reset-full.sql once. Then edit config.js with your Supabase URL, anon key and admin email. Admin is email-based, not UID-based.</p><div class="badge-row"><span class="badge">1. Run SQL</span><span class="badge">2. Edit config.js</span><span class="badge">3. Login with admin email</span></div></div></section>`}
async function globalClick(e){const routeBtn=e.target.closest('[data-route]'); if(routeBtn){e.preventDefault(); location.hash=routeBtn.dataset.route; return} if(e.target.closest('#openLogin')){authModal();return} if(e.target.closest('#logout')){await sb?.auth.signOut(); S.user=null; S.profile=null; updateAccount(); route(); toast('Logged out'); return} const js=e.target.closest('[data-join-squad]'); if(js){joinSquad(js.dataset.joinSquad);return} const bp=e.target.closest('[data-buy-plan]'); if(bp){buyPlan(bp.dataset.buyPlan);return} const bs=e.target.closest('[data-buy-service]'); if(bs){buyService(bs.dataset.buyService);return} const au=e.target.closest('[data-admin-user]'); if(au){adminUser(au.dataset.adminUser);return} const as=e.target.closest('[data-admin-service]'); if(as){adminService(as.dataset.adminService);return} const ap=e.target.closest('[data-admin-payment]'); if(ap){adminPayment(ap.dataset.adminPayment);return} if(e.target.closest('[data-refresh-admin]')){await loadAdminData(); route(); toast('Admin refreshed')}}
async function globalSubmit(e){const f=e.target; if(f.id==='authForm'){e.preventDefault(); const email=f.email.value.trim(), password=f.password.value; const mode=f.mode.value; let res=mode==='signup'?await sb.auth.signUp({email,password}):await sb.auth.signInWithPassword({email,password}); if(res.error)return toast(res.error.message); await auth(); await loadAll(); document.querySelector('.auth-modal')?.remove(); route(); toast('Welcome to StackOps');}
 if(f.id==='profileForm'){e.preventDefault(); if(!needLogin())return; const data=Object.fromEntries(new FormData(f)); await sb.from('profiles').update(data).eq('id',uid()); await loadProfile(); updateAccount(); toast('Profile saved'); route();}
 if(f.id==='squadForm'){e.preventDefault(); if(!needLogin())return; const data=Object.fromEntries(new FormData(f)); data.owner_id=uid(); const {error}=await sb.from('squads').insert(data); if(error)return toast(error.message); await loadSquads(); toast('Squad published'); route();}
 if(f.id==='serviceForm'){e.preventDefault(); if(!needLogin())return; const data=Object.fromEntries(new FormData(f)); data.owner_id=uid(); data.price_inr=Number(data.price_inr||0); data.status='pending'; const {error}=await sb.from('services').insert(data); if(error)return toast(error.message); await loadServices(); toast('Submitted for admin approval'); route();}
 if(f.id==='postForm'){e.preventDefault(); if(!needLogin())return; const data=Object.fromEntries(new FormData(f)); data.user_id=uid(); data.display_name=S.profile?.display_name||S.user.email; const {error}=await sb.from('posts').insert(data); if(error)return toast(error.message); await loadPosts(); toast('Posted'); route();}}
function authModal(){if(!sb)return toast('Add Supabase URL/key in config.js first'); const div=document.createElement('div'); div.className='auth-modal'; div.innerHTML=`<form id="authForm" class="auth-box card forms"><button type="button" class="circle close-x" onclick="this.closest('.auth-modal').remove()">×</button><p class="eyebrow">Secure login</p><h2>Enter StackOps</h2><input name="email" type="email" placeholder="Email" required><input name="password" type="password" placeholder="Password" required><select name="mode"><option value="login">Login</option><option value="signup">Create account</option></select><button class="btn">Continue</button></form>`; document.body.appendChild(div)}
function needLogin(){if(!S.user){authModal();return false} if(!sb){toast('Supabase not configured'); return false} return true}
async function joinSquad(id){if(!needLogin())return; const {error}=await sb.from('squad_invites').insert({squad_id:id,user_id:uid(),status:'pending'}); toast(error?error.message:'Invite request sent')}
async function buyPlan(plan_key){if(!needLogin())return; const p=S.plans.find(x=>x.plan_key===plan_key); const {error}=await sb.from('payments').insert({user_id:uid(),plan_key,amount_inr:p?.price_inr||0,purpose:'plan',status:'pending'}); toast(error?error.message:'Payment request created. Admin can verify it.')}
async function buyService(id){if(!needLogin())return; const s=S.services.find(x=>String(x.id)===String(id)); const amount=Number(s?.price_inr||0); const {error}=await sb.from('payments').insert({user_id:uid(),service_id:id,amount_inr:amount,platform_commission_inr:Math.round(amount*(Number(s?.commission_percent||15)/100)),purpose:'service',status:'pending'}); toast(error?error.message:'Service booking request created')}
async function adminUser(val){if(!isAdmin())return; const [action,id]=val.split(':'); const patch=action==='approve'?{account_status:'approved',is_banned:false}:action==='verify'?{is_verified:true,badge:'Verified Gamer'}:{account_status:'banned',is_banned:true}; const {error}=await sb.from('profiles').update(patch).eq('id',id); if(error)return toast(error.message); await loadAdminData(); route(); toast('User updated')}
async function adminService(val){const [status,id]=val.split(':'); const {error}=await sb.from('services').update({status}).eq('id',id); if(error)return toast(error.message); await loadAdminData(); route(); toast('Service updated')}
async function adminPayment(val){const [status,id]=val.split(':'); const {error}=await sb.from('payments').update({status,verified_by:uid(),verified_at:new Date().toISOString()}).eq('id',id); if(error)return toast(error.message); toast('Payment updated'); await loadAdminData(); route()}
function bindProfileUpload(){}
function localPlans(){return[{plan_key:'free',name:'Free',price_inr:0,badge:'Starter',title:'Rookie',perks:['Basic profile','Join squads']},{plan_key:'spark',name:'Spark',price_inr:299,badge:'Spark Badge',title:'Rising Duelist',perks:['Profile flair','More invites']},{plan_key:'silver',name:'Silver',price_inr:999,badge:'Silver Badge',title:'Squad Regular',perks:['Priority squads','Animated badge']},{plan_key:'gold',name:'Gold',price_inr:2499,badge:'Gold Elite',title:'Elite Player',perks:['Boosted discovery','Premium banner']},{plan_key:'diamond',name:'Diamond',price_inr:5999,badge:'Diamond Pro',title:'Pro Grinder',perks:['Coach boost','VIP support']},{plan_key:'legend',name:'Legend',price_inr:10000,badge:'Crown Badge',title:'StackOps Legend',perks:['Crown identity','Top placement','Founder-style glow']}];}
function localSquads(){return[{id:'demo1',name:'Night Queue Demons',game:'Valorant',region:'India',rank_required:'Gold+',description:'Chill comms, serious executes, 10 PM daily.'},{id:'demo2',name:'Mumbai Aim Lab',game:'Valorant',region:'Mumbai',rank_required:'Any',description:'Warmup, deathmatch, then comp.'},{id:'demo3',name:'Radiant Rush',game:'Valorant',region:'Singapore',rank_required:'Ascendant+',description:'Tournament-style play and vod reviews.'}]}
function localServices(){return[{id:'svc1',title:'Valorant Aim Coaching',description:'60-minute routine and crosshair discipline session.',game:'Valorant',category:'coaching',price_inr:499,commission_percent:15,status:'approved'},{id:'svc2',title:'Rank Push Duo Review',description:'VOD review with role-specific notes.',game:'Valorant',category:'rank-review',price_inr:999,commission_percent:15,status:'approved'}]}
function localPosts(){return[{content:'Need one controller for 5-stack tonight. Good comms only.',display_name:'NeonByte',created_at:new Date().toISOString()},{content:'Offering free 10-min aim check for first 5 gamers.',display_name:'CoachViper',created_at:new Date().toISOString()}]}
function localLive(){return[{tag:'LIVE',hot:true,title:'Squad requests are moving',text:'Gamers can request invites and admins can monitor community flow.',a:'Fast invites',b:'Rank filters'},{tag:'EARNING',title:'Coaching can become marketplace revenue',text:'Service creators sell sessions and you keep platform commission.',a:'15% commission',b:'Admin approval'},{tag:'IDENTITY',title:'Profiles feel premium',text:'Titles, badges and admin crowns make status visible instantly.',a:'Crown admin',b:'Verified'}]}
